// Built-in loop & one-shot library (all CC0 — Sonic Pi sample pack,
// originally from freesound.org; see ../SOUND_LIBRARY.md).
export const LOOPS = [
  { cat: "Drums", name: "Industrial beat", path: "loops/loop_industrial" },
  { cat: "Drums", name: "Compus groove", path: "loops/loop_compus" },
  { cat: "Drums", name: "Garzul break", path: "loops/loop_garzul" },
  { cat: "Drums", name: "Mika beat", path: "loops/loop_mika" },
  { cat: "Drums", name: "Safari percussion", path: "loops/loop_safari" },
  { cat: "Drums", name: "Tabla loop", path: "loops/loop_tabla" },
  { cat: "Drums", name: "Perc loop 1", path: "loops/loop_perc1" },
  { cat: "Drums", name: "Perc loop 2", path: "loops/loop_perc2" },
  { cat: "Drums", name: "Mehackit beat 1", path: "loops/loop_mehackit1" },
  { cat: "Drums", name: "Mehackit beat 2", path: "loops/loop_mehackit2" },
  { cat: "Electronic", name: "Electric loop", path: "loops/loop_electric" },
  { cat: "Electronic", name: "3D printer groove", path: "loops/loop_3d_printer" },
  { cat: "Electronic", name: "Weirdo loop", path: "loops/loop_weirdo" },
  { cat: "Electronic", name: "Drone in G", path: "loops/loop_drone_g_97" },
  { cat: "Guitar", name: "Guitar Em9", path: "loops/guit_em9" },
  { cat: "Guitar", name: "Guitar E fifths", path: "loops/guit_e_fifths" },
  { cat: "Guitar", name: "Guitar harmonics", path: "loops/guit_harmonics" },
  { cat: "Guitar", name: "Guitar E slide", path: "loops/guit_e_slide" },
  { cat: "Bass", name: "Woodsy bass (C)", path: "loops/bass_woodsy_c" },
  { cat: "Bass", name: "Voxy bass (C)", path: "loops/bass_voxy_c" },
  { cat: "Bass", name: "Thick bass (C)", path: "loops/bass_thick_c" },
  { cat: "Textures", name: "Ambient piano", path: "loops/ambi_piano" },
  { cat: "Textures", name: "Ambient choir", path: "loops/ambi_choir" },
  { cat: "Textures", name: "Vinyl hiss", path: "sonicpi/vinyl_hiss" },
];
